
# Spring boot info
spring:
  application:
    name: '@artifactId@'

  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/seonier
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/H2/seonier;MODE=MySQL;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:db/schema.sql';
    username: sa
    password:
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5

  # MariaDB로 변경 시 삭제.
  h2:
    console:
      enabled: true
      path: /h2/console

#  config:
#    import:
#      - optional:file:/opt/app-root/etc/conf/application-external.yaml
  profiles:
    group:
      dev: dev
      stage: stage
      prod: prod

  thymeleaf:
    cache: false
#    mode: HTML5

  web:
    resources:
      add-mappings: false
  ai:
    openai:
      api-key: ENC(pif1sV53mh2HAJtkZodCV/84zMmvwnG0gVfjH1+NJj624x6JINpYIH//3HiFT7axu39V06D10H7u3kWT1hAXFigI2Zu7O9jCWcT0Nd09sDlDI0JbfKukNGifc53IQygL3EWuHRmyp2PlaYvAPkEdJGBJRio0M4J71prAyTlyqc+mpy4aH63HXgbSPpvf0YPGxyg6aCPqC37LkK0DVbx75zEUyPCzc/BRtlOLKuhz0W/ssdkkPay+UHfPavF2AM+ulmpPb9j2ZPY9eY9LUMBjrw==)

# Mybatis 설정
mybatis:
  config-location: classpath:com/seonier/persistence/mybatis-config.xml
  mapper-locations: classpath:com/seonier/persistence/mapper/**/*.xml
  type-aliases-package: com.seonier.dto.request,seonier.kt.dto.response,com.seonier.persistence.model

# Server info
server:
  compression:
    enabled: true
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never
    page: /error
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: '/'
  shutdown: graceful

  tomcat:
    # https://oingdaddy.tistory.com/224
    # Springboot 기동시 Failed to scan : FileNotFoundException *.jar 오류
    additional-tld-skip-patterns: '*.jar'

# Actuator properties
management:
  endpoint:
    env:
      show-values: always
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - env
          - health
          - info
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  info:
    env:
      enabled: true

# Application info
info:
  app:
    env:          '${spring.profiles.active:@env@}'
    group:        '@groupId@'
    artifact:     '@artifactId@'
    version:      '@version@'
    name:         '@name@'
    description:  '@description@'

prompt: |
  너는 사용자의 건강상태, 희망 급여, 연령, 직업 이력, 주거지 위치 등을 고려해 아래 일자리 중 적합한 일자리 5개를 추천하는 평가 모델이야.

  1. 일자리 리스트를 너에게 제공할 거야.
  일자리의 정보들이 담겨있고, 일자리 마다 정보의 나열 순서는 다음과 같아.
  '직업 이름', '업무 명', '직무 상세 내용', '필요한 자격, 면허', '계약 기간', '급여 정보', '근무 시간', '휴게 시간', '복지 조건', '근무지 주소', '위도', '경도', '인근 전철역', '버스 노선 번호'
  '-'값은 공백란이야.
  
  *고용24에 올라온 일자리 리스트*
    1. '승합차 운전원', '차량 운행', '교육센터 아이들의 안전한 등하원', '운전 면허', '', '시급 15000원 이상', '14:30~18:00, 주 4일', '-', '고용보험, 산재보험, 퇴직금', '대전광역시 서구 대덕대로 150 305호 (갈마동, 큰마을아파트)', '36.346846', '127.375863', '-', '-'
    2. '환경미화원', '조경 관리', '골프장 그린관리(볼마크)', '-', '6개월', '월급 220만원 이상', '08:00~17:00, 주 5일', '12:00~13:00', '국민연금, 고용보험, 산재보험, 건강보험', '대전광역시 유성구 유성대로1689번길 69, 대덕복지센터 (전민동)', '36.392064', '127.384197', '-', '-'
    3. '요양보호사', '요양 보호', '주간 보호센터 요양 보호', '요양 보호사, 운전 면허', '6개월', '월급 209만원 이상', '08:00~18:00, 주 5일', '2시간', '국민연금, 고용보험, 산재보험, 건강보험, 퇴직금', '대전광역시 서구 유등로 507(용문동)', '36.337764', '127.383136', '대전 1호선 용문역 1번 출구 1KM', '315318602'
    4. '데스크 안내원', '프런트 안내', '프런트 안내', '-', '12개월', '월급 240만원 이상', '개장 05:30~14:30 /정시 10:00~19:00 /마감 13:00~22:00 ,주 5일', '-', '국민연금, 고용보험, 산재보험, 건강보험, 퇴직연금', '대전광역시 유성구 대덕대로 581, 사이언스도룡스포츠센터 (도룡동)', '36.374235', '127.364865', '-', '-'
    5. '공업기계 설치·정비원', '공업기계 설치 및 정비', '공기압축기 유지보수/ 각종 소모품 교체/ AS 및 Overhaul', '운전 면허', '-', '연봉 3000만원 이상', '09:00~18:00, 주 5일', '12:00~13:00', '국민연금, 고용보험, 산재보험, 건강보험, 퇴직연금', '대전광역시 유성구 탑립동 테크노2로 281 (탑립동)', '36.429471', '127.379018', '-', '-'
    6. '건물 보수원 및 영선원', '시설관리 야간기사', '대림연구소 시설관리 야간기사', '가스기능사', '12개월', '월급 258만원', '평일 19:00~익일 08:30 야간근무, 토요일 12:30~익일 08:30, 일요일, 공휴일 08:30~익일 08:30', '평일 야간근무 4.5 / 토요일 근무 5.5 / 일요일, 공휴일 근무 6.5', '국민연금, 고용보험, 산재보험, 건강보험, 퇴직금', '대전광역시 유성구 신성동 신성남로 106, 디엘케미칼(대림연구소)', '36.392849', '127.353872', '-', '-'
    7. 'Java 프로그래머', '개발 및 유지보수', '공공 SI개발 및 유지보수 업무', '-', '-', '연봉 4000만원', '09:00~18:00, 주 5일', '12:00~13:00', '국민연금, 고용보험, 산재보험, 건강보험, 퇴직연금', '대전광역시 서구 문정로90번길 11, 탄방동,미래빌딩5층 (탄방동)', '36.346683', '127.387413', '대전 1호선 탄방 4번출구 500M', '-'
    8. '건축시공 기술자', '건설공무', '계약, 공무, 기성 청구 등 전반적인 관급건설 공무관리업무', '-', '-', '월급 220만원 이상', '09:00~18:00, 주 5일', '12:00~13:00', '국민연금, 고용보험, 산재보험, 건강보험, 퇴직금', '대전광역시 유성구 죽동로279번길 25, 1층 (주)에이치비건영', '36.392064', '127.384197', '-', '-'
    9. '제품 생산 관리자', '제품 생산 및 품질관리', '복합재료 제품 생산 계획 수립 및 관리/최적화 작업/운영 및 감독', '-', '-', '연봉 3500만원 이상', '08:00~17:00, 주 5일', '12:00~13:00', '국민연금, 고용보험, 산재보험, 건강보험, 퇴직연금', '대전광역시 유성구 국제과학로 46', '36.386911', '127.375406', '-', '-'
    10. '건설·채굴 단순 종사원', '각종 안전시설물 설치 및 해체', '각종 안전 가설 안전난간대 등 안전시설물 전체 설치 및 해체업무', '-', '-', '월급 300만원 이상', '07:00~17:00, 주 6일', '07:00~07:30/12:00~13:00', '국민연금, 고용보험, 산재보험, 퇴직금', '대전광역시 유성구 진잠옛로176번길 317-101', '36.3098', '127.3089', '-', '-'

  2. 사용자의 정보를 제공할거고, 정보들의 나열 순서는 다음과 같아.
    사용자 생년월일: {{AGE}}
    주소: {{ADDR}}
    성별: {{GENDER}}
    직업: {{OCCUPATION}}
    보유 질병: {{DISEASE}}
    사용자 입력 질병: {{CUSTOM_DISEASE}}
  
  각 일자리에 대해 **100점 만점 기준으로 적합도 점수(score)를 계산**하고, 추천 사유(reason)를 간단히 설명한 뒤, 가장 적합한 5개를 추천해줘.

  응답 형식은 어래와 같이 JSON Array를 String으로 주고, 마크다운 형식은 사용하지 말아줘.
  [
    {
      "score": 93,
      "reason": "추천 점수가 높게 나온 이유를 두 줄 이내로 설명",
      "job_title": "직업 이름",
      "job_task": "업무 명",
      "job_desc": "직무 상세 내용",
      "job_license_required": "필요한 자격, 면허",
      "job_contract_period": "계약 기간",
      "job_salary": "급여 정보",
      "job_work_hours": "근무 시간",
      "job_break_time": "휴게 시간",
      "job_benefits": "복지 조건",
      "job_address": "근무지 주소",
      "job_latitude": "위도",
      "job_longitude": "경도",
      "job_nearby_subway": "인근 전철역",
      "job_bus_routes": "버스 노선 번호"
    }
  ]

---
# Development environment
spring:
  config:
    activate:
      on-profile: dev

---
# Staging environment
spring:
  config:
    activate:
      on-profile: stage

---
# Production environment
spring:
  config:
    activate:
      on-profile: prod

  # If you do not want property defaults to be applied you can set spring.devtools.add-properties to false in your application.properties.
  devtools:
    add-properties: false
    restart:
      enabled: false


decorator:
  datasource:
    p6spy:
      enable-logging: false

# ── H2 콘솔 활성화

# (이미 datasource 설정이 있다면 위에 붙여넣으시면 됩니다)

